
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Position Controllers ---------------------------------------
cb_rev_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: sema/cb/dummy_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
